# Generated by Django 4.2.4 on 2024-04-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Public',
        ),
    ]
