# Generated by Django 4.2.4 on 2024-04-28 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
